[workspace]
members = ["hodu-backend-interp"]
resolver = "2"

[workspace.dependencies]
hodu_cpu_kernels = { path = "../hodu/crates/hodu_cpu_kernels" }
hodu_plugin_sdk = { path = "../hodu/crates/hodu_plugin_sdk" }
