# Hodu Official Plugin Registry
# This file is used by `hodu plugin install <name>` to find plugins.

[[plugin]]
name = "aot-cpu"
description = "AOT compiler for CPU via C code generation"
git = "https://github.com/daminstudio/hodu-plugins"
path = "hodu-backend-aot-cpu-plugin"
versions = [
  # { version = "0.1.0", tag = "aot-cpu-v0.1.0", plugin = "0.3" },
]
