[plugin]
name = "aot-cpu"
version = "0.1.0"
type = "backend"

[backend]
runner = true
builder = true
devices = ["CPU"]
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "aarch64-apple-darwin"]
